
export const responsive = {

    superLargeDesktop: {
        // the naming can be any, depends on you.
        breakpoint: { max: 4000, min: 1024 },
        items: 5,
    },
    desktop: {
        breakpoint: { max: 1024, min: 800 },
        items: 4,
    },
    tablet: {
        breakpoint: { max: 800, min: 464 },
        items: 2,
    },
    mobile: {
        breakpoint: { max: 464, min: 0 },
        items: 1,
    },
};

const imageStyle = {
    width: "300px",
    marginLeft: "30px"

}


const gradeData1 = [
    {
        id: 0,
        imagePath: <img src={require('../common/imag/CG-Process/cashew-nut-bgi1.jpg')} style={imageStyle} />,
        gradeName: 'WW-180',
        tradeName: "white wholes-180",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "170-180",
        maxMoisture: "5%",
        maxBroken: "5%",
        description:"WW-180 cashews are the largest type of cashew and are considered the best grade. They are also known as the King of Cashews because they are larger, have superior taste, and are more expensive than other cashews.",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },

    {
        id: 1,
        //imagePath: <img src={require('../imag/wholes-grade/A210.png')} style={imageStyle} />,
        gradeName: 'WW-210',
        tradeName: "white wholes 210",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "200-210",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 2,
        // imagePath: <img src={require('../imag/wholes-grade/a240.png')} style={imageStyle} />,
        gradeName: 'WW-240',
        tradeName: "white wholes 240",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "220-240",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 3,
        // imagePath: <img src={require('../imag/wholes-grade/a320.png')} style={imageStyle} />,
        gradeName: 'WW-320',
        tradeName: "white wholes 320",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "300-320",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 4,
        // imagePath: <img src={require('../imag/wholes-grade/asw.png')} style={imageStyle} />,
        gradeName: 'WW-450',
        tradeName: "white wholes 450",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "400-450",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 5,
        // imagePath: <img src={require('../imag/wholes-grade/asw.png')} style={imageStyle} />,
        gradeName: 'WW-500',
        tradeName: "white wholes 500",
        averagePrice: "700",
        cashewColor: "white / pale ivory light ash",
        cashewCount: "450-500",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Remarks: Kernels shall be completely free from infestation, insect damage,  mould rancidity, adhering testa and objectionable extraneous matter.Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 6,
        // imagePath: <img src={require('../imag/wholes-grade/dw.png')} style={imageStyle} />,
        gradeName: 'SW-180',
        tradeName: "Scroched Wholes 180",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "170-180",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 7,
        // imagePath: <img src={require('../imag/wholes-grade/ssw.png')} style={imageStyle} />,
        gradeName: 'SW-210',
        tradeName: "Scroched Wholes 210",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "220-240",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 8,
        // imagePath: <img src={require('../imag/wholes-grade/sw.png')} style={imageStyle} />,
        gradeName: 'SW-240',
        tradeName: "Scroched Wholes-240",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "220-240",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 9,
        // imagePath: <img src={require('../imag/wholes-grade/w150.png')} style={imageStyle} />,
        gradeName: 'SW-320',
        tradeName: "white wholes 180",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "300-320",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 10,
        // imagePath: <img src={require('../imag/wholes-grade/w180.png')} style={imageStyle} />,
        gradeName: 'SW-450',
        tradeName: "Scroched Wholes-450",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "400-450",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 11,
        // imagePath: <img src={require('../imag/wholes-grade/w240.png')} style={imageStyle} />,
        gradeName: 'SW-500',
        tradeName: "Scroched Wholes 500",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched /  slightly darkened due to over-heating while roasting or drying in drier/borma",
        cashewCount: "450-500",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 12,
        // imagePath: <img src={require('../imag/wholes-grade/w320.png')} style={imageStyle} />,
        gradeName: 'SSW',
        tradeName: "Scorched Wholes Seconds",
        averagePrice: "700",
        cashewColor: "Kernels may be overscorched,",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter.",
    },
    {
        id: 13,
        // imagePath: <img src={require('../imag/wholes-grade/w400.png')} style={imageStyle} />,
        gradeName: 'DW',
        tradeName: "Desort Wholes",
        averagePrice: "700",
        cashewColor: "Kernels may be deep scorched, deep brown,",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: " Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter.",
    },
    {
        id: 14,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'B',
        tradeName: "Butts",
        averagePrice: "700",
        cashewColor: "White/pale ivory or light ash. Kernels broken cross-wise (evenly or unevenly) naturally attached",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 15,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'S',
        tradeName: "Splits",
        averagePrice: "700",
        cashewColor: "	White/pale ivory or light ash. Kernels Split naturally lengthwise",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 16,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'LWP',
        tradeName: "large White Pices",
        averagePrice: "700",
        cashewColor: "White/pale ivory or light ash",
        cashewCount: "Kernels broken into more than two pieces andnot passing through 4 mesh 16 SWG sieve/4.75mm.I.S.Sieve",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 17,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SWP',
        tradeName: "Small White Pieces",
        averagePrice: "700",
        cashewColor: "White/pale ivory or light ash",
        cashewCount: "Broken Kernels smaller than those described on LWP but not passing through 6 mesh 20 SWG Sieve/2.80 mm I.S. Sieve",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 18,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'BB',
        tradeName: "Baby Bits",
        averagePrice: "700",
        cashewColor: "do",
        cashewCount: "Plemules and broken Kernels smaller than those described as SWP but not Passing through a 10 mesh 24SWG Sieve/1.70mm I..S. Sieve",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 19,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SB',
        tradeName: "Scroched Butts",
        averagePrice: "700",
        cashewColor: "	Kernels broken crosswise (evenly or unevenly) and naturally attached. Kernels may be scorched/slightly darkened due to over heating while roasting or drying in the drier/borma",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel. ",
    },
    {
        id: 20,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SS',
        tradeName: "Scroched Splits",
        averagePrice: "700",
        cashewColor: "Kernels split naturally lengthwise. Kernels may be scorched/slightly darkened due to overheating while Roasting or drying in drier/borma",
        cashewCount: "N.A",
        maxMoisture: "5%",
        maxBroken: "5%",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 21,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SP',
        tradeName: "Scroched Pieces",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched/slightly darkened due to overheating while roasting or drying in drier/borma",
        cashewCount: "Pieces passing through a mesh 16 SWG sieve/4.75 mm I.S. Sieve",
        maxMoisture: "5%",
        maxBroken: "Nil",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 22,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SSP',
        tradeName: "Scroched Small Pieces",
        averagePrice: "700",
        cashewColor: "Kernels may be scorched/slightly darkened due to overheating while roasting or drying in drier/borma",
        cashewCount: "Pieces smaller than SP but not passing through a 6mesh 20 SWG Sieve/2.80 mm I.S. Sieve",
        maxMoisture: "5%",
        maxBroken: "Nil",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter. Scraped and partially shrivelled kernels also permitted provided such scraping/shrivelling does not affect the characteristic shape of the kernel.",
    },
    {
        id: 23,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'SPS',
        tradeName: "Scroched Pieces Seconds",
        averagePrice: "700",
        cashewColor: "Kernels may be overscorched immature, shrivelled (Pirival) speckled(Karaniram) discoloured",
        cashewCount: "Kernels broken into pieces but not passing through a 4 mesh 16 SWG sieve/4.75 mm I.S. Sieve",
        maxMoisture: "5%",
        maxBroken: "Nil",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter.",
    },
    {
        id: 24,
        // imagePath: <img src={require('../imag/wholes-grade/ww.png')} style={imageStyle} />,
        gradeName: 'DP',
        tradeName: "Desert Pieces",
        averagePrice: "700",
        cashewColor: "Kernels may be deep scorched, deep Brown, blue, speckled, discoloured and black spotted",
        cashewCount: "Kernels broken into pieces but not passing through a 4 mesh 16 SWG sieve/4.75 mm and I.S.Sieve",
        maxMoisture: "5%",
        maxBroken: "Nil",
        remark: "Kernels shall be completely free from infestation, insect damage, mould rancidity, adhering testa and objectionable extraneous matter.",
    },
  

];
export default gradeData1;

